### ISSUE TITLE
Release the latest apk?

### ISSUE THREAD

**Issue by wby238** [jakev/SqlCipherHook#3]
For some reason I can't build the apk, so could you please build the latest apk?
I am using an Android 4.4.4 VM.

**Comment by jakev** [comment]
Interesting. Few questions:

- What kind of error are you getting? 
- What command are you running to try to build?
- what version of Android Studio/gradle are you using?

I updated the `build.gradle` offline to build with Android Studio 3.0+ and will add the commits this evening. I don't mind sharing an updated APK with you, but ultimately I'd rather determine the root cause. :)

**Comment by jakev** [comment]
I just pushed a commit to build with newer Android Studio (https://github.com/jakev/SqlCipherHook/commit/708ce45026ac16ca342f3d99fa94047ffd5f690c). Do you mind trying to build again and sharing the results?

**Comment by wby238** [comment]
Oh, sorry.
I can't build it because of the Internet.
I ask my friend to build it and it was success builed.
